version: '3.8'
services:
  client:
    container_name: ${CLIENT_CONTAINER_NAME}
    image: ${CLIENT_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    networks:
      - bayes-classifier-network
networks:
  bayes-classifier-network:
    driver: bridge
    name: bayes-classifier-network
    external: true