version: '3.8'
services:
  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile.api
    env_file:
      - ./.env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    ipc: ${IPC}
    runtime: ${RUNTIME}
    depends_on:
      - db
    networks:
      - bayes-classifier-network

  db:
    image: mongo:latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    restart: always
    volumes:
      - type: bind
        source: ${MONGO_DATA_SOURCE}
        target: ${MONGO_DATA_TARGET}
    networks:
      - bayes-classifier-network
networks:
  bayes-classifier-network:
    driver: bridge
    name: bayes-classifier-network