version: '3.8'
services:
  bayes-classifier:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - bayes-classifier-network
networks:
  bayes-classifier-network:
    driver: bridge
    name: bayes-classifier-network